# Generated by Django 4.1.5 on 2023-01-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_reservations_users_rooms_user_reservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations_users_rooms',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservations_users_rooms',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
