# Generated by Django 4.1.5 on 2023-01-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_reservations_users_rooms_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations_users_rooms',
            name='checkin_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservations_users_rooms',
            name='checkout_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservations_users_rooms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservations_users_rooms',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
