# Generated by Django 4.1.5 on 2023-01-05 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_reservations_users_rooms_user_reservations'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_reservations',
            field=models.ManyToManyField(related_name='user_reservations', through='users.Reservations_users_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
