# Generated by Django 4.1.5 on 2023-01-05 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_reservations_users_rooms_checkin_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0002_room_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_reservations',
            field=models.ManyToManyField(related_name='user_reservations', through='users.Reservations_users_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
