# Generated by Django 4.1.5 on 2023-01-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_room_reservations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_reservations',
        ),
    ]
