# Generated by Django 4.1.5 on 2023-01-05 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("0", "Péssimo"),
                            ("1", "Ruim"),
                            ("2", "Regular"),
                            ("3", "Bom"),
                            ("4", "Muito Bom"),
                            ("5", "Excelente"),
                            ("Not Informed", "Default"),
                        ],
                        default="Not Informed",
                        max_length=12,
                    ),
                ),
                (
                    "feedbacks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="hotels.hotel",
                    ),
                ),
            ],
        ),
    ]
