# Generated by Django 4.1.5 on 2023-01-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0002_rename_feedbacks_feedback_hotel_feedback_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="description",
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.CharField(
                choices=[
                    (0, "Péssimo"),
                    (1, "Ruim"),
                    (2, "Regular"),
                    (3, "Bom"),
                    (4, "Muito Bom"),
                    (5, "Excelente"),
                ],
                default=5,
                max_length=12,
            ),
        ),
    ]
