# Generated by Django 4.1.5 on 2023-01-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0003_feedback_description_alter_feedback_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="description",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.CharField(
                choices=[
                    (0, "Péssimo"),
                    (1, "Ruim"),
                    (2, "Regular"),
                    (3, "Bom"),
                    (4, "Muito Bom"),
                    (5, "Excelente"),
                ],
                max_length=12,
            ),
        ),
    ]
